{
 "title": "JAWSX",
 "description": "VIPER",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_epoch_int{job=\"EU1_cardano_block\"}",
     "legendFormat": "jaws_core_node_suomi"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotInEpoch_int{job=\"EU1_cardano_block\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Chain Density",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_density_real{job=\"EU1_cardano_block\"} * 100",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_density_real{job=\"EU1_cardano_relay\"} * 100",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_density_real{job=\"EU2_cardano_block\"} * 100",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_density_real{job=\"EU2_cardano_relay\"} * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "EU1 System Health",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk Utilization"
    }
   ]
  },
  {
   "title": "Pool Performance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_Forge_forged_int / cardano_node_metrics_Forge_node_is_leader_int * 100)",
     "legendFormat": "JAWS_Core"
    }
   ]
  },
  {
   "title": "Blocks Forged",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int",
     "legendFormat": "JAWS_Core"
    }
   ]
  },
  {
   "title": "Finland",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds)"
    }
   ]
  },
  {
   "title": "Germany",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds)"
    }
   ]
  },
  {
   "title": "Blocks Assigned",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int",
     "legendFormat": "JAWS_Core"
    }
   ]
  },
  {
   "title": "DE1 System Health",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk Utilization"
    }
   ]
  },
  {
   "title": "K1 System Health",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk Utilization"
    }
   ]
  },
  {
   "title": "S-Korea",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds)"
    }
   ]
  },
  {
   "title": "S1Core",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_upTime_ns / (3599999999999.971)"
    }
   ]
  },
  {
   "title": "S1Relay1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_upTime_ns / (3599999999999.971)"
    }
   ]
  },
  {
   "title": "S1Relay2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_upTime_ns / (3599999999999.971)"
    }
   ]
  },
  {
   "title": "DE1Core",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_upTime_ns / (3599999999999.971)"
    }
   ]
  },
  {
   "title": "DE1Core",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_upTime_ns / (3599999999999.971)"
    }
   ]
  },
  {
   "title": "K1Core",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_upTime_ns / (3599999999999.971)"
    }
   ]
  },
  {
   "title": "K1Relay",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_upTime_ns / (3599999999999.971)"
    }
   ]
  },
  {
   "title": "Slot height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int",
     "legendFormat": "JAWS_S1_Core"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int",
     "legendFormat": "JAWS_S1_Relay1"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int",
     "legendFormat": "JAWS_S1_Relay2"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int",
     "legendFormat": "JAWS_DE1_Core"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int",
     "legendFormat": "JAWS_DE1_Relay"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int",
     "legendFormat": "JAWS_K1_Core"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int",
     "legendFormat": "JAWS_K1_Relay"
    }
   ]
  },
  {
   "title": "RAM S1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 10 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Total Ram"
    }
   ]
  },
  {
   "title": "S1 Core TX's processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int",
     "legendFormat": "JAWS_Core"
    }
   ]
  },
  {
   "title": "System Load S1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load 1m" },
    { "expr": "node_load5", "legendFormat": "Load 5m" },
    { "expr": "node_load15", "legendFormat": "Load 15m" }
   ]
  },
  {
   "title": "S1 Relay 1 TX's processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int",
     "legendFormat": "JAWS_Relay"
    }
   ]
  },
  {
   "title": "Disk S1",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 13 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "jaws_relay"
    }
   ]
  },
  {
   "title": "S1 Relay 2 TX's processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int",
     "legendFormat": "JAWS_Relay"
    }
   ]
  },
  {
   "title": "RAM DE1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 16 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Total Ram"
    }
   ]
  },
  {
   "title": "DE1 Core TX's processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int",
     "legendFormat": "JAWS_Core"
    }
   ]
  },
  {
   "title": "System Load K1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load 1m" },
    { "expr": "node_load5", "legendFormat": "Load 5m" },
    { "expr": "node_load15", "legendFormat": "Load 15m" }
   ]
  },
  {
   "title": "System Load DE1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load 1m" },
    { "expr": "node_load5", "legendFormat": "Load 5m" },
    { "expr": "node_load15", "legendFormat": "Load 15m" }
   ]
  },
  {
   "title": "Block height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int",
     "legendFormat": "JAWS_S1_Core"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int",
     "legendFormat": "JAWS_S1_Relay1"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int",
     "legendFormat": "JAWS_S1_Relay2"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int",
     "legendFormat": "JAWS_DE1_Core"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int",
     "legendFormat": "JAWS_DE1_Relay"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int",
     "legendFormat": "JAWS_K1_Core"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int",
     "legendFormat": "JAWS_K1_Relay"
    }
   ]
  },
  {
   "title": "Disk DE1",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 18 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "jaws_relay"
    }
   ]
  },
  {
   "title": "DE1 Relay 1 TX's processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int",
     "legendFormat": "JAWS_Relay"
    }
   ]
  },
  {
   "title": "RAM K1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 20 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Total Ram"
    }
   ]
  },
  {
   "title": "K1 Core TX's processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int",
     "legendFormat": "JAWS_Core"
    }
   ]
  },
  {
   "title": "Disk K1",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 22 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "jaws_relay"
    }
   ]
  },
  {
   "title": "K1 Relay 1 TX's processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int",
     "legendFormat": "JAWS_Relay"
    }
   ]
  },
  {
   "title": "S1 Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_ChainDB_metrics_blockNum_int[150s]) *60",
     "legendFormat": "JAWS_S1_Core"
    },
    {
     "expr": "rate (cardano_node_ChainDB_metrics_blockNum_int[150s]) *60",
     "legendFormat": "JAWS_S1_R1"
    },
    {
     "expr": "rate (cardano_node_ChainDB_metrics_blockNum_int[150s]) *60",
     "legendFormat": "JAWS_S1_R2"
    }
   ]
  },
  {
   "title": "DE1 Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_ChainDB_metrics_blockNum_int[150s]) *60",
     "legendFormat": "JAWS_DE1_Core"
    },
    {
     "expr": "rate (cardano_node_ChainDB_metrics_blockNum_int[150s]) *60",
     "legendFormat": "JAWS_DE1_R1"
    }
   ]
  },
  {
   "title": "K1 Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_ChainDB_metrics_blockNum_int[150s]) *60",
     "legendFormat": "JAWS_K1_Core"
    },
    {
     "expr": "rate (cardano_node_ChainDB_metrics_blockNum_int[150s]) *60",
     "legendFormat": "JAWS_K1_R1"
    }
   ]
  },
  {
   "title": "Time Synchronization S1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds",
     "legendFormat": "Est. error(s)"
    },
    { "expr": "node_timex_offset_seconds", "legendFormat": "Offset: Node vs. Ref." },
    { "expr": "node_timex_maxerror_seconds", "legendFormat": "Max. Error (s)" }
   ]
  },
  {
   "title": "Time Synchronization DE1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds",
     "legendFormat": "Est. error(s)"
    },
    { "expr": "node_timex_offset_seconds", "legendFormat": "Offset: Node vs. Ref." },
    { "expr": "node_timex_maxerror_seconds", "legendFormat": "Max. Error (s)" }
   ]
  },
  {
   "title": "Time Synchronization K1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds",
     "legendFormat": "Est. error(s)"
    },
    { "expr": "node_timex_offset_seconds", "legendFormat": "Offset: Node vs. Ref." },
    { "expr": "node_timex_maxerror_seconds", "legendFormat": "Max. Error (s)" }
   ]
  },
  {
   "title": "Memory Utilization S1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "JAWS_S1_Core"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "JAWS_S1_R1"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "JAWS_S1_R2"
    }
   ]
  },
  {
   "title": "Memory Utilization DE1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "JAWS_DE1_Core"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "JAWS_DE1_R1"
    }
   ]
  },
  {
   "title": "Memory Utilization K1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "JAWS_K1_Core"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "JAWS_K1_R1"
    }
   ]
  },
  {
   "title": "S1 Mempool Transactions",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "JAWS_S1_Core"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "JAWS_S1_R1"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "JAWS_S1_R2"
    }
   ]
  },
  {
   "title": "DE1 Mempool Transactions",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "JAWS_DE1_Core"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "JAWS_DE1_R1"
    }
   ]
  },
  {
   "title": "K1 Mempool Transactions",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "JAWS_K1_Core"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "JAWS_K1_R1"
    }
   ]
  },
  {
   "title": "Connected Peers S1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int",
     "legendFormat": "JAWS_S1_Core"
    },
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int",
     "legendFormat": "JAWS_S1_Relay1"
    },
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int",
     "legendFormat": "JAWS_S1_Relay2"
    }
   ]
  },
  {
   "title": "Connected Peers DE1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int",
     "legendFormat": "JAWS_DE1_Core"
    },
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int",
     "legendFormat": "JAWS_DE1_Relay1"
    }
   ]
  },
  {
   "title": "Connected Peers K1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int",
     "legendFormat": "JAWS_K1_Core"
    },
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int",
     "legendFormat": "JAWS_K1_Relay1"
    }
   ]
  },
  {
   "title": "S1 max \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used /(1024*1024)",
     "legendFormat": "JAWS_S1_Core"
    },
    {
     "expr": "rts_gc_max_bytes_used /(1024*1024)",
     "legendFormat": "JAWS_S1_R1"
    },
    {
     "expr": "rts_gc_max_bytes_used /(1024*1024)",
     "legendFormat": "JAWS_S1_R2"
    }
   ]
  },
  {
   "title": "DE1 max \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used /(1024*1024)",
     "legendFormat": "JAWS_DE1_Core"
    },
    {
     "expr": "rts_gc_max_bytes_used /(1024*1024)",
     "legendFormat": "JAWS_DE1_R1"
    }
   ]
  },
  {
   "title": "K1 max \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used /(1024*1024)",
     "legendFormat": "JAWS_K1_Core"
    },
    {
     "expr": "rts_gc_max_bytes_used /(1024*1024)",
     "legendFormat": "JAWS_K1_R1"
    }
   ]
  },
  {
   "title": "S1 current \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "JAWS_S1_Core"
    },
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "JAWS_S1_R1"
    },
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "JAWS_S1_R2"
    }
   ]
  },
  {
   "title": "DE1 current \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "JAWS_DE1_Core"
    },
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "JAWS_DE1_R1"
    }
   ]
  },
  {
   "title": "K1 current \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "JAWS_K1_Core"
    },
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "JAWS_K1_R1"
    }
   ]
  },
  {
   "title": "Core Nodes peak memory allocated (from OS, in MBytes)",
   "type": "graph",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "Jaws_S1_Core"
    },
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "Jaws_DE1_Core"
    },
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "Jaws_K1_Core"
    }
   ]
  },
  {
   "title": "Core File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "JAWS_S1" },
    { "expr": "node_filefd_allocated", "legendFormat": "JAWS_DE1" },
    { "expr": "node_filefd_allocated", "legendFormat": "JAWS_K1" }
   ]
  },
  {
   "title": "Core Node RSS (allocated memory in RAM, in MB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(cardano_node_metrics_Stat_rss_int*4096)/(1024*1026)",
     "legendFormat": "JAWS_S1"
    },
    {
     "expr": "(cardano_node_metrics_Stat_rss_int*4096)/(1024*1026)",
     "legendFormat": "JAWS_DE1"
    },
    {
     "expr": "(cardano_node_metrics_Stat_rss_int*4096)/(1024*1026)",
     "legendFormat": "JAWS_K1"
    }
   ]
  },
  {
   "title": "S1 Core Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1h])) * 3600",
     "legendFormat": "S1 Core 1h Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[1h])) * 3600",
     "legendFormat": "S1 Core 1h Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "K1 Core Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1h])) * 3600",
     "legendFormat": "K1 Core 1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[1h])) * 3600",
     "legendFormat": "K1 Core 1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "DE1 Core Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1h])) * 3600",
     "legendFormat": "DE1 Core 1h Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[1h])) * 3600",
     "legendFormat": "DE1 Core 1h Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "S1 peak memory allocated (from OS, in MBytes)",
   "type": "graph",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "Jaws_S1_Core"
    },
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "Jaws_S1_R1"
    },
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "Jaws_S1_R2"
    }
   ]
  },
  {
   "title": "DE1 peak memory allocated (from OS, in MBytes)",
   "type": "graph",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "Jaws_DE1_R1"
    },
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "Jaws_DE1_Core"
    }
   ]
  },
  {
   "title": "K1 peak memory allocated (from OS, in MBytes)",
   "type": "graph",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "Jaws_K1_Core"
    },
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "Jaws_K1_R1"
    }
   ]
  },
  {
   "title": "S1 Relay 1 Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1h])) * 3600",
     "legendFormat": "S1 Relay 1 1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[1h])) * 3600",
     "legendFormat": "S1 Relay 1 1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "K1 Relay 1 Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 73 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1h])) * 3600",
     "legendFormat": "K1 Relay 1 1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[1h])) * 3600",
     "legendFormat": "K1 Relay 1 1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "DE1 Relay 1 Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 73 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1h])) * 3600",
     "legendFormat": "DE1 Relay 1 1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[1h])) * 3600",
     "legendFormat": "DE1 Relay 1 1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "S1 Mempool Transactions",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "JAWS_S1_Core"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "JAWS_S1_R1"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "JAWS_S1_R2"
    }
   ]
  },
  {
   "title": "DE1 Mempool Transactions",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "JAWS_DE1_Core"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "JAWS_DE1_R1"
    }
   ]
  },
  {
   "title": "K1 Mempool Transactions",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "JAWS_K1_Core"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "JAWS_K1_R1"
    }
   ]
  },
  {
   "title": "S1 File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "JAWS_S1_Core" },
    { "expr": "node_filefd_allocated", "legendFormat": "JAWS_S1_R1" },
    { "expr": "node_filefd_allocated", "legendFormat": "JAWS_S1_R2" }
   ]
  },
  {
   "title": "DE1 File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "JAWS_DE1_Core" },
    { "expr": "node_filefd_allocated", "legendFormat": "JAWS_DE1_R1" }
   ]
  },
  {
   "title": "K1 File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "JAWS_K1_Core" },
    { "expr": "node_filefd_allocated", "legendFormat": "JAWS_K1_Core" }
   ]
  }
 ]
}