
#./entrypoint.sh 


version: '3.7'

volumes:
  #grafana-storage:
  grafana-share:
  #prometheus-storage:
  #redis-storage:
  #redis-data:

secrets:
  grafana_admin_password:
    file: ./secrets/mainnet/grafana_admin_password.txt
  grafana.ini:
    file: ./secrets/mainnet/grafana.ini
  gocnode.yaml:
    file: ./secrets/mainnet/gocnode.yaml
  node_kes.key:
    file: ./secrets/mainnet/node_kes.key
  node_vrf.key:
    file: ./secrets/mainnet/node_vrf.key
  node.cert:
    file: ./secrets/mainnet/node.cert
  
services:
  #---------------------------------------------------------------------------------                                                                                                                        
  producer0:
    image: adakailabs/multi_cardano_pool:21.09.03
    user: lovelace
    ports:
       - "3100:3001"
    secrets:
      - source: node_kes.key
        uid: '1000'
        gid: '1000'
        mode: 0400

      - source: node_vrf.key
        uid: '1000'
        gid: '1000'
        mode: 0400

      - source: node.cert
        uid: '1000'
        gid: '1000'
        mode: 0400

      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400

    command:
      - "start-node"
      - "--id"
      - "0"
      - "--is-producer"

    volumes:
      - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.com.adakailabs.adakai-vm00 == true
  #---------------------------------------------------------------------------------
  relay0:
    # deploy:
    #   resources:
    #     limits:
    #       cpus: 1
    #       memory: 9G
          #reservations:
          #  cpus: 0.25
          #  memory: 128M
    depends_on:
      - "redis"
      - "optimizer"
    image: adakailabs/multi_cardano_pool:21.09.03
    command:
      - "start-node"
      - "--id"
      - "0"
    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400
        
    ports:
      - "3002:3001"
    volumes:
      - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.com.adakailabs.picolo-zbook == true
  #---------------------------------------------------------------------------------

  relay1:
    #depends_on:
    #  - "producer0"
    image: adakailabs/multi_cardano_pool:21.09.03
    command:
      - "start-node"
      - "--id"
      - "1"
    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400
        
    ports:
      - "3003:3001"
    volumes:
      - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.com.adakailabs.goku-proliant == true
          #- node.labels.com.adakailabs.adakai-swarm04 == true
  #---------------------------------------------------------------------------------

  relay2:
    depends_on:
      - "producer0"
    image: adakailabs/multi_cardano_pool:21.09.03
    command:
      - "start-node"
      - "--id"
      - "2"
    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400
        
    ports:
      - "3004:3001"
    volumes:
      - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.com.adakailabs.goku-proliant == true
  #---------------------------------------------------------------------------------

  optimizer:
    image: adakailabs/multi_cardano_optimizer:21.09.00
    depends_on:
      - "redis"
    command:
      - "start-optim"

    secrets:
      - source: gocnode.yaml

    volumes:
      - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/

    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400

    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.com.adakailabs.adakai-tiny01 == true
#-----------------------------------------------------------------------
  # monitor:
  #   image: adakailabs/cardano-monitor:21.01.02
  #   depends_on:
  #     - "relay0"
  #   command:
  #     - "start-rtview"
  #   ports:
  #     - "8666:8666"
  #   volumes:
  #     - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/

  #   secrets:
  #     - source: gocnode.yaml
  #       uid: '1000'
  #       gid: '1000'
  #       mode: 0400
      
  #   deploy:
  #     restart_policy:
  #       condition: any     
  #     placement:
  #       constraints:
  #         - node.labels.com.adakailabs.monitor == true

  #---------------------------------------------------------------------------------          
  prometheus:
    image: adakailabs/multi_prometheus:21.09.00
    command:
      - "start-prometheus"
    ports:
      - "9090:9090"
    volumes:
      - /mnt/cardano_shares/mainnet/prometheus:/prometheus

    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400

    deploy:
      restart_policy:
        condition: any     
          
  #---------------------------------------------------------------------------------          
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - "relay0"
      - "prometheus"
    user: 1000:1000
    ports:
      - "3666:3000"
    volumes:
      - /mnt/cardano_shares/mainnet/grafana/lib/:/var/lib/grafana
      - grafana-share:/var/share/grafana
    #environment:
    #  - GF_PATHS_CONFIG=/run/secrets/grafana.ini
    deploy:
      restart_policy:
        condition: any     

  #---------------------------------------------------------------------------------
  redis:
    image: redis:latest
    user: 1000:1000
    command:
      - /config/redis.conf
    ports:
       - "6379:6379"
    volumes:
      - /mnt/cardano_shares/mainnet/redis/config:/config
      - /mnt/cardano_shares/mainnet/redis/lib:/var/lib/redis
      - /mnt/cardano_shares/mainnet/redis/data:/data
      - /mnt/cardano_shares/mainnet/redis/log:/var/log/redis
      
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.com.adakailabs.adakai-vm00 == true
#--------------------------------------------------------------------------    
  telegraf:
    image: telegraf:latest
    depends_on:
      - "influxdb"
    ports:	
       - "8125:8125"
       - "8092:8092"
       - "8094:8094"
    volumes:
      - /mnt/cardano_shares/testnet/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /usr/share/snmp/mibs:/usr/share/snmp/mibs
      - /var/lib/snmp:/var/lib/snmp
    deploy:
      restart_policy:
        condition: any     
    #  placement:
    #    constraints:
    #      - node.labels.com.adakailabs.raspberry4 == true

  #---------------------------------------------------------------------------------          
  influxdb:
    image: influxdb:1.8.0
    ports:	
      - "8086:8086"
    volumes:
      - /mnt/cardano_shares/mainnet/influxdb/data:/var/lib/influxdb/data

    deploy:
      restart_policy:
        condition: any     
