
#./entrypoint.sh 


version: '3.7'

volumes:
  grafana-storage:
  grafana-share:
  prometheus-storage:
  redis-storage:
  redis-data:

secrets:
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt	
  gocnode.yaml:
    file: ./secrets/gocnode.yaml
  redis.conf:
    file: ./secrets/redis.conf
  

services:
          
  #---------------------------------------------------------------------------------
  relay0:
    #depends_on:
    #  - "producer0"
    image: adakailabs/multi_cardano_pool:21.09.00
    command:
      - "start-node"
      - "--id"
      - "0"
    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400
        
    ports:
      - "3002:3001"
    volumes:
      - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.com.adakailabs.raspberry1 == true
  
  #---------------------------------------------------------------------------------

  relay1:
    #depends_on:
    #  - "producer0"
    image: adakailabs/multi_cardano_pool:21.09.00
    command:
      - "start-node"
      - "--id"
      - "1"
    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400
        
    ports:
      - "3003:3001"
    volumes:
      - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.com.adakailabs.adakai-swarm04 == true
  #---------------------------------------------------------------------------------

  relay2:
    #depends_on:
    #  - "producer0"
    image: adakailabs/multi_cardano_pool:21.09.00
    command:
      - "start-node"
      - "--id"
      - "2"
    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400
        
    ports:
      - "3004:3001"
    volumes:
      - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.com.adakailabs.adakai-vm00 == true

  #---------------------------------------------------------------------------------
  # #---------------------------------------------------------------------------------                                                                                                                                                                                
  optimizer:
    image: adakailabs/multi_cardano_optimizer:21.09.00
    depends_on:
      - "redis"
    command:
      - "start-optim"

    secrets:
      - source: gocnode.yaml

    volumes:
      - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/

    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400

    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.com.adakailabs.adakai-tiny01 == true

#-----------------------------------------------------------------------                                                                                                                                                                                              
  redis:
    image: redis:latest
    #depends_on:                                                                                                                                                                                                                                                      
    #  - "relay0"                                                                                                                                                                                                                                                     
    command:
      - /run/secrets/redis.conf

    secrets:
      - redis.conf
    #user: 1000:1000                                                                                                                                                                                                                                                  
    ports:
       - "6379:6379"
    volumes:
      - redis-storage:/var/lib/redis
      - redis-data:/data
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.com.adakailabs.adakai-tiny01 == true

#--------------------------------------------------------------------------  
  # monitor:
  #   image: adakailabs/cardano-monitor:21.01.02
  #   depends_on:
  #     - "relay0"
  #   command:
  #     - "start-rtview"
  #   ports:
  #     - "8666:8666"
  #   volumes:
  #     - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/

  #   secrets:
  #     - source: gocnode.yaml
  #       uid: '1000'
  #       gid: '1000'
  #       mode: 0400
      
  #   deploy:
  #     restart_policy:
  #       condition: any     
  #     placement:
  #       constraints:
  #         - node.labels.com.adakailabs.monitor == true

  #---------------------------------------------------------------------------------          
  prometheus:
    image: adakailabs/cardano-prometheus:latest
    depends_on:
      - "relay0"
    command:
      - "start-prometheus"
    ports:
      - "9090:9090"
    volumes:
      - prometheus-storage:/prometheus

    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400

    deploy:
      restart_policy:
        condition: any     
      placement:
        constraints:
          - node.labels.com.adakailabs.monitor == true
          
  #---------------------------------------------------------------------------------          
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - "relay0"
      - "prometheus"
    secrets:
      - grafana_admin_password
    user: 1000:1000
    ports:
      - "3666:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - grafana-share:/var/share/grafana
    environment:
      #  - GF_PATHS_DATA=/home/lovelace/grafana/var/lib/grafana
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
    deploy:
      restart_policy:
        condition: any     
      placement:
        constraints:
          - node.labels.com.adakailabs.monitor == true

