version: '3.7'

secrets:
    my_secret:
      file: ./test-secret
#    my_other_secret:
#      external: true

services:
    relay0:
      image: adakailabs/cardano-relay:latest
      command:
        - "relay0"
        - "0"
      ports:
        - "3100:3100"
      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.relay0 == true
    relay1:
      image: adakailabs/cardano-relay:latest
      command:
        - "relay1"
        - "1"
      ports:
        - "3101:3101"
      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.relay1 == true

    producer0:
      image: adakailabs/cardano-relay:latest
      secrets:
        - my_secret
 #       - my_other_secret
      command:
        - "producer0"
        - "2"
      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.producer0 == true
            
    monitor:
      image: adakailabs/cardano-monitor:21.01.02
      command:
        - "2" # 2 relays
        - "1" # 1 producer
      ports:
        - "8666:8666"

      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.monitor == true

    prometheus:
      image: adakailabs/cardano-prometheus:latest

      command:
        - "2" # 2 relays
        - "1" # 1 producer
      ports:
        - "9090:9090"
      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.monitor == true

