version: '3.7'

services:
    relay0:
      image: adakailabs/cardano-relay:21.01.00
      command:
        - "relay0"
        - "0"
      ports:
        - "3100:3100"
        - "12798:12798"
        - "9100:9100"
      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.relay0 == true
#    relay1:
#      image: adakailabs/cardano-relay:21.01.00
#      command:
#        - "relay1"
#        - "1"
#      ports:
#        - "3110:3110"
#        - "12798:12798"
#        - "9101:9101"
#      volumes:
#        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
#      deploy:
#        placement:
#          constraints:
#            - node.labels.com.adakailabs.relay1 == true

    producer0:
      image: adakailabs/cardano-relay:21.01.00
      command:
        - "producer0"
        - "2"
      ports:
        - "3120:3120"
        - "12798:12798"
        - "9102:9102"
      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.producer0 == true
            
    monitor:
      image: adakailabs/cardano-monitor:21.01.02
      command:
        - "2" # 2 relays
        - "1" # 1 producer
      ports:
        - "6660:6660"
        - "8666:8666"

      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.monitor == true

    prometheus:
      image: adakailabs/cardano-prometheus:21.01.00
      ports:
        - "9090:9090"
      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.monitor == true

