version: '3.7'

volumes:
  grafana-storage:

secrets:
    grafana_admin_password:
      file: ./secrets/grafana_admin_password.txt	
    kes_key.skey:
      file: ./secrets/pool_kes.skey
    vrf_skey.skey:
      file: ./secrets/pool_vrf.skey
    operational_certificate.cert:
      file: ./secrets/pool.cert

services:
    relay0:
      image: adakailabs/cardano-relay:latest
      command:
        - "relay0"
        - "0"
        - "no" #not a producer
      ports:
        - "3100:3100"
      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.relay0 == true
    relay1:
      image: adakailabs/cardano-relay:latest
      command:
        - "relay1"
        - "1"
        - "no" #not a producer
      ports:
        - "3101:3101"
      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.relay1 == true

    producer0:
      image: adakailabs/cardano-relay:latest
      secrets:
        - kes_key.skey
        - vrf_skey.skey
        - operational_certificate.cert
      command:
        - "producer0"
        - "2"
      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.producer0 == true
            
    monitor:
      image: adakailabs/cardano-monitor:21.01.02
      command:
        - "2" # 2 relays
        - "1" # 1 producer
      ports:
        - "8666:8666"

      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.monitor == true

    prometheus:
      image: adakailabs/cardano-prometheus:latest
      
      command:
        - "2" # 2 relays
        - "1" # 1 producer
        - "no" #not a producer
      ports:
        - "9090:9090"
      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.monitor == true
    grafana:
      image: grafana/grafana:latest
      secrets:
        - grafana_admin_password
      user: 1000:1000
      ports:
        - "3000:3000"
      volumes:
        - grafana-storage:/var/lib/grafana
      environment:
      #  - GF_PATHS_DATA=/home/lovelace/grafana/var/lib/grafana
         - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.monitor == true
