
#./entrypoint.sh 


version: '3.9'

volumes:
  grafana-storage:
  grafana-share:
  prometheus-storage:
  redis-storage:
  redis-data:


secrets:
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt
  redis.conf:
    file: ./secrets/redis.conf
  node_kes.key:
    file: ./secrets/node_kes.key
  node_vrf.key:
    file: ./secrets/node_vrf.key
  node.cert:
    file: ./secrets/node.cert
  gocnode.yaml:
    file: ./secrets/gocnode.yaml
  

services:
  #---------------------------------------------------------------------------------
  producer0:
    image: adakailabs/multi_cardano_pool:21.08.01
    user: lovelace
    ports:
       - "5100:3001"
    secrets:
      - source: node_kes.key
        uid: '1000'
        gid: '1000'
        mode: 0400
        
      - source: node_vrf.key
        uid: '1000'
        gid: '1000'
        mode: 0400

      - source: node.cert
        uid: '1000'
        gid: '1000'
        mode: 0400

      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400
 
    command:
      - "start-node"
      - "--id"
      - "0"
      - "--is-producer"
      - "--log-min-severity"
      - "Info"
      
    volumes:
      - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
    deploy:
      restart_policy:
        condition: any     
      placement:
        constraints:
          - node.labels.com.adakailabs.raspberry2 == true


  #---------------------------------------------------------------------------------          
  relay0:
    depends_on:
      - "producer0"
    image: adakailabs/multi_cardano_pool:21.08.01
    command:
      - "start-node"
      - "--id"
      - "0"
      - "--log-min-severity"
      - "Info"
      
    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400
        
    ports:
      - "5000:3001"
    volumes:
      - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.com.adakailabs.raspberry3 == true

  relay1:
    depends_on:
      - "producer0"
    image: adakailabs/multi_cardano_pool:21.08.02
#    cap_add:
#      - ALL
#      - NET_RAW
#      - NET_BIND_SERVICE
#      - NET_ADMIN
    command:
      - "start-node"
      - "--id"
      - "1"
      - "--log-min-severity"
      - "Info"
      
    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400
        
    ports:
      - "5001:3001"
    volumes:
      - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.com.adakailabs.relay1 == true


  optimizer:
    image: adakailabs/cardano-optimizer:latest
    depends_on:
      - "redis"
    cap_add:
#      - ALL
      - NET_RAW
#      - NET_BIND_SERVICE
#      - NET_ADMIN
    command:
      - "start-optim"
#      - "--log-min-severity"
#      - "Info"
      
    secrets:
      - source: gocnode.yaml
        
    volumes:
      - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/

    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400
      
    deploy:
      restart_policy:
        condition: any     
      placement:
        constraints:
          - node.labels.com.adakailabs.relay0 == true
         

  monitor:
    image: adakailabs/cardano-monitor:21.05.02
    depends_on:
      - "relay0"
    command:
      - "start-rtview"
    ports:
      - "8666:8666"
    volumes:
      - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/

    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400
      
    deploy:
      restart_policy:
        condition: any     
      placement:
        constraints:
          - node.labels.com.adakailabs.relay0 == true

  #---------------------------------------------------------------------------------          
  prometheus:
    image: adakailabs/cardano-prometheus:latest
    depends_on:
      - "relay0"
    command:
      - "start-prometheus"
    ports:
      - "9090:9090"
    volumes:
      - prometheus-storage:/prometheus

    secrets:
      - source: gocnode.yaml
        uid: '1000'
        gid: '1000'
        mode: 0400

    deploy:
      restart_policy:
        condition: any     
      placement:
        constraints:
          - node.labels.com.adakailabs.relay0 == true
          
  #---------------------------------------------------------------------------------          
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - "relay0"
      - "prometheus"
    secrets:
      - grafana_admin_password
    user: 1000:1000
    ports:
      - "3666:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - grafana-share:/var/share/grafana
    environment:
      #  - GF_PATHS_DATA=/home/lovelace/grafana/var/lib/grafana
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
    deploy:
      restart_policy:
        condition: any     
      placement:
        constraints:
          - node.labels.com.adakailabs.relay0 == true

  #---------------------------------------------------------------------------------          
  redis:
    image: redis:latest
    #depends_on:
    #  - "relay0"
    command:
      - /run/secrets/redis.conf
             
    secrets:
      - redis.conf
    #user: 1000:1000
    ports:	
       - "6379:6379"
    volumes:
      - redis-storage:/var/lib/redis
      - redis-data:/data
    #environment:
      #  - GF_PATHS_DATA=/home/lovelace/grafana/var/lib/grafana
    deploy:
      restart_policy:
        condition: any     
      placement:
        constraints:
          - node.labels.com.adakailabs.relay0 == true

