---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: "Update Repository cache"
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
    # - name: "Update cache & Full system update"
    #   apt:
    #     update_cache: true
    #     upgrade: dist
    #     cache_valid_time: 3600
    #     force_apt_get: true
    - name: "install packages"
      apt:
        update_cache: true
        state: present
        name:
          - nfs-common
          - tmux
          - ufw
          - htop
          - chrony
          - curl
          - rsync
          - emacs-nox
          - wget
          - snmp-mibs-downloader
          - snmp
          - autofs
          - git
          - curl
          - wget
          
    #- name: "line insert"
    #  lineinfile:
    #    path: "/etc/fstab"
    #    backup: yes
    #    line: '192.168.100.57:/mnt/cardano-shares    /mnt/cardano_shares    nfs    defaults    0 0'
    #    insertbefore: BOF

    - name: Unmount
      mount:
        path: /home/lovelace/ws
        state: absent

    - name: Unmount
      mount:
        path: /mnt/cardano_shares
        state: absent

        
    # - name: umount 
    #   command: umount 
    #   args:
    #     warn: no
    #   become: true

    # - name: umount 
    #   command: umount /mnt/cardano_shares
    #   args:
    #     warn: no
    #   become: true

      
    # - name: "Example1: Validate if a String or line is present in the file"
    #   tags: oldnfs
    #   lineinfile:
    #     path: /etc/fstab
    #     # The String to Search
    #     search_string: "192.168.100.*" 
    #     # The String to Replace
    #     line: "# replaced line"
    #     state: present
    #   register: example1out

    
    - name: create mnt dir
      command: mkdir -p /mnt
      args:
        warn: no
      become: true
        
    - name: copy auto.master file to remote server
      copy:
        src: ./auto.master
        dest: /etc  

    - name: copy auto.master file to remote server
      copy:
        src: ./auto.nfs
        dest: /etc  

    - name: Restart service autofs
      service:
        name: autofs
        state: restarted

    - name: copy docker installer file to remote server
      copy:
        src: ./docker-install.sh
        dest: /usr/local/bin
        mode: a+x
        
    #- name: Run a script with arguments (free form)
    #  shell: /usr/local/bin/docker-install.sh
      
    #- name: Update and upgrade apt packages
    #  apt:
    #    update_cache: yes
    #    upgrade: 'yes'
        
