version: '3.7'

services:
    relay:
      image: adakailabs/cardano-relay:21.01.00 
      ports:
        - "3100:3100"
        - "12798:12798"
      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.relay == true

    monitor:
      image: adakailabs/cardano-monitor:21.01.01 
      ports:
        - "6660:6660"
        - "8666:8666"
      volumes:
        - /home/lovelace/cardano-node/:/home/lovelace/cardano-node/
      deploy:
        placement:
          constraints:
            - node.labels.com.adakailabs.monitor == true

