{
 "title": "Cardano: Application metrics v3",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Peers Producer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{job=\"producer0-cardano\"}",
     "legendFormat": "Current Epoch"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int{job=\"producer0-cardano\"}",
     "legendFormat": "Expiry Kes Period"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateStartKESPeriod_int{job=\"producer0-cardano\"}",
     "legendFormat": "Kes Start"
    }
   ]
  },
  {
   "title": "About to Lead",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forge_about_to_lead_int",
     "legendFormat": "About to lead"
    },
    {
     "expr": "cardano_node_metrics_Forge_node_not_leader_int",
     "legendFormat": "Not Leader"
    },
    {
     "expr": "cardano_node_metrics_Forge_forge_about_to_lead_int - cardano_node_metrics_Forge_node_not_leader_int",
     "legendFormat": "XXX"
    }
   ]
  },
  {
   "title": "Pool Performance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_Forge_forged_int / cardano_node_metrics_Forge_node_is_leader_int * 100)",
     "legendFormat": "Pool"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_thermal_zone_temp", "legendFormat": "temp-{{instance}}" }
   ]
  },
  {
   "title": "Adopted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_adopted_int"
    }
   ]
  },
  {
   "title": "Slot in Epoc",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((cardano_node_metrics_slotInEpoch_int{instance=\"producer0:12798\"}) / 432000) * 100"
    }
   ]
  },
  {
   "title": "Is Leader / Adopted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int",
     "legendFormat": "IsLeader"
    },
    {
     "expr": "cardano_node_metrics_Forge_adopted_int",
     "legendFormat": "Adopted"
    }
   ]
  },
  {
   "title": "Forged / Forged Adopted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int",
     "legendFormat": "Forged"
    },
    {
     "expr": "cardano_node_metrics_blocksForgedNum_int",
     "legendFormat": "Forged Num"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"relay0-exporter\"} / (node_memory_MemTotal_bytes{job=\"relay0-exporter\"})))* 100",
     "legendFormat": "Mem 0"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"relay1-exporter\"} / (node_memory_MemTotal_bytes{job=\"relay1-exporter\"})))* 100",
     "legendFormat": "Mem 1"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"relay2-exporter\"} / (node_memory_MemTotal_bytes{job=\"relay2-exporter\"})))* 100",
     "legendFormat": "Mem 2"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"producer0-exporter\"} / (node_memory_MemTotal_bytes{job=\"producer0-exporter\"})))* 100",
     "legendFormat": "Mem p"
    }
   ]
  },
  {
   "title": "Peers Producer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{job=\"relay0-cardano\"}",
     "legendFormat": "Peers Relay 0"
    },
    {
     "expr": "cardano_node_metrics_connectedPeers_int{job=\"relay1-cardano\"}",
     "legendFormat": "Peers Relay 1"
    },
    {
     "expr": "cardano_node_metrics_connectedPeers_int{job=\"relay2-cardano\"}",
     "legendFormat": "Peers Relay 2"
    },
    {
     "expr": "cardano_node_metrics_connectedPeers_int{job=\"producer0-cardano\"}",
     "legendFormat": "Peers Producer"
    }
   ]
  },
  {
   "title": "Remaining KES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int{instance=\"producer0:12798\"}"
    }
   ]
  },
  {
   "title": "Slots Missed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotsMissedNum_int"
    }
   ]
  },
  {
   "title": "Producer Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"producer0-exporter\"}",
     "legendFormat": "Load 1min"
    },
    {
     "expr": "node_load5{job=\"producer0-exporter\"}",
     "legendFormat": "Load 5min"
    },
    {
     "expr": "node_load15{job=\"producer0-exporter\"}",
     "legendFormat": "Load 15min"
    }
   ]
  },
  {
   "title": "Relay0 Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"relay0-exporter\"}",
     "legendFormat": "Load 1min"
    },
    {
     "expr": "node_load5{job=\"relay0-exporter\"}",
     "legendFormat": "Load 5min"
    },
    {
     "expr": "node_load15{job=\"relay0-exporter\"}",
     "legendFormat": "Load 15min"
    }
   ]
  },
  {
   "title": "Relay1 Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"relay1-exporter\"}",
     "legendFormat": "Load 1min"
    },
    {
     "expr": "node_load5{job=\"relay1-exporter\"}",
     "legendFormat": "Load 5min"
    },
    {
     "expr": "node_load15{job=\"relay1-exporter\"}",
     "legendFormat": "Load 15min"
    }
   ]
  },
  {
   "title": "Forged / Forged Adopted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_adopted_int",
     "legendFormat": "Load 1min"
    },
    {
     "expr": "cardano_node_metrics_Forge_forged_int",
     "legendFormat": "Load 5min"
    },
    {
     "expr": "cardano_node_metrics_blocksForgedNum_int",
     "legendFormat": "Load 15min"
    },
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int * -1",
     "legendFormat": "Load 15min"
    }
   ]
  },
  {
   "title": "Producer Status ",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{mode=\"idle\", job=\"producer0-exporter\"}[1m]) * 100)",
     "legendFormat": "CPU Load {{cpu}}"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"producer0-exporter\"} / (node_memory_MemTotal_bytes{job=\"producer0-exporter\"})))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=\"producer0-exporter\"} / node_memory_SwapTotal_bytes{job=\"producer0-exporter\"})) * 100",
     "legendFormat": "Swap Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/home/lovelace/cardano-node\", job=\"producer0-exporter\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/home/lovelace/cardano-node\", job=\"producer0-exporter\"})",
     "legendFormat": "Disk Utilization "
    }
   ]
  },
  {
   "title": "Relay0 Status ",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{mode=\"idle\", job=\"relay0-exporter\"}[1m]) * 100)",
     "legendFormat": "CPU Load {{cpu}}"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"relay0-exporter\"} / (node_memory_MemTotal_bytes{job=\"relay0-exporter\"})))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=\"relay0-exporter\"} / node_memory_SwapTotal_bytes{job=\"relay0-exporter\"})) * 100",
     "legendFormat": "Swap Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/home/lovelace/cardano-node\", job=\"relay0-exporter\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/home/lovelace/cardano-node\", job=\"relay0-exporter\"})",
     "legendFormat": "Disk Utilization "
    }
   ]
  },
  {
   "title": "Relay1 Status ",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 5, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{mode=\"idle\", job=\"relay1-exporter\"}[1m]) * 100)",
     "legendFormat": "CPU Load {{cpu}}"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"relay1-exporter\"} / (node_memory_MemTotal_bytes{job=\"relay1-exporter\"})))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=\"relay1-exporter\"} / node_memory_SwapTotal_bytes{job=\"relay1-exporter\"})) * 100",
     "legendFormat": "Swap Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/home/lovelace/cardano-node\", job=\"relay1-exporter\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/home/lovelace/cardano-node\", job=\"relay1-exporter\"})",
     "legendFormat": "Disk Utilization "
    }
   ]
  },
  {
   "title": "Relay2 Status ",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 5, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{mode=\"idle\", job=\"relay2-exporter\"}[1m]) * 100)",
     "legendFormat": "CPU Load {{cpu}}"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"relay2-exporter\"} / (node_memory_MemTotal_bytes{job=\"relay2-exporter\"})))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=\"relay2-exporter\"} / node_memory_SwapTotal_bytes{job=\"relay2-exporter\"})) * 100",
     "legendFormat": "Swap Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/home/lovelace/cardano-node\", job=\"relay2-exporter\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/home/lovelace/cardano-node\", job=\"relay2-exporter\"})",
     "legendFormat": "Disk Utilization "
    }
   ]
  },
  {
   "title": "Node Memory Used (%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{alias!~\"monitoring.*\"} / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory Used (%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{alias!~\"monitoring.*\"} / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "{{cpu}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Node Bandwidth (bps)",
   "type": "graph",
   "description": "20 second rolling time average",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 30 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "description": "20 second rolling time average",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Platform Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"relay0:9100\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 37 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "node_thermal_zone_temp", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Producer 0 Memory Used",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((node_memory_MemTotal_bytes{job=\"producer0-exporter\"} - node_memory_MemAvailable_bytes{job=\"producer0-exporter\"})/1024/1024)/(node_memory_MemTotal_bytes{job=\"producer0-exporter\"}/1024/1024))*100",
     "legendFormat": "used-{{instance}}"
    }
   ]
  },
  {
   "title": "RELAY 0 Memory Used",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((node_memory_MemTotal_bytes{job=\"relay0-exporter\"} - node_memory_MemAvailable_bytes{job=\"relay0-exporter\"})/1024/1024)/(node_memory_MemTotal_bytes{job=\"relay0-exporter\"}/1024/1024))*100",
     "legendFormat": "used-{{instance}}"
    }
   ]
  },
  {
   "title": "RELAY 1 Memory Used",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((node_memory_MemTotal_bytes{job=\"relay1-exporter\"} - node_memory_MemAvailable_bytes{job=\"relay1-exporter\"})/1024/1024)/(node_memory_MemTotal_bytes{job=\"relay1-exporter\"}/1024/1024))*100",
     "legendFormat": "used-{{instance}}"
    }
   ]
  },
  {
   "title": "RELAY 1 Memory Used",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((node_memory_MemTotal_bytes{job=\"relay2-exporter\"} - node_memory_MemAvailable_bytes{job=\"relay2-exporter\"})/1024/1024)/(node_memory_MemTotal_bytes{job=\"relay2-exporter\"}/1024/1024))*100",
     "legendFormat": "used-{{instance}}"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} - node_memory_MemAvailable_bytes{alias!~\"monitoring.*\"})/1024/1024",
     "legendFormat": "used-{{instance}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{alias!~\"monitoring.*\"}/1024/1024",
     "legendFormat": "total-{{instance}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Node max \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used/(1024*1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node current \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(time()-node_boot_time_seconds)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slots to Epoc End",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(60*60*24*5) - cardano_node_metrics_slotInEpoch_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cardano Chain Density",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_blockNum_int[150s])*60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node peak memory allocated (from OS, in MBytes)",
   "type": "graph",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UxTxo Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(cardano_node_metrics_utxoSize_int)/1000000"
    }
   ]
  },
  {
   "title": "Cardano Slot Height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slot length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 65 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[60s])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Last Block Height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rejected blocks since last restart",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int - cardano_node_metrics_Forge_adopted_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slots Missed per hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_slotsMissedNum_int[1h]) * 3600",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cardano Slot Height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cardano Last Block Slot",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slot leading share (% of slots led)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 79 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_Forge_node_is_leader_int[710s])/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[710s])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(cardano_node_metrics_Forge_node_is_leader_int[710s])/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[710s]))",
     "legendFormat": "Total led slots"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slots Missed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotsMissedNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node RSS (allocated memory in RAM, in MB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(cardano_node_metrics_Stat_rss_int*4096)/(1024*1026)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Transactions / per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 86 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_txsProcessedNum_int[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tx In Mempool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 86 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(cardano_node_metrics_txsInMempool_int[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Stat_threads_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "In Bandwidth",
   "type": "graph",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT non_negative_derivative(mean(\"ifHCInOctets\"), 1s)  *8 AS \"ln\" FROM \"snmp\" WHERE (\"hostname\" = 'TL-R600VPN' AND \"ifName\" = 'eth0') AND $timeFilter GROUP BY time($__interval), \"hostname\", \"ifName\" fill(null)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " *8" ], "type": "math" },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "TL-R600VPN" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT non_negative_derivative(mean(\"ifHCInOctets\"), 1s)  *8 AS \"ln\" FROM \"snmp\" WHERE (\"hostname\" = 'TL-R600VPN' AND \"ifName\" = 'eth0') AND $timeFilter GROUP BY time($__interval), \"hostname\", \"ifName\" fill(null)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       },
       { "params": [ " *8" ], "type": "math" },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "TL-R600VPN" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "Average Ping to Google",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "192.168.100.1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "192.168.100.1" }
     ]
    }
   ]
  },
  {
   "title": "Average Ping to Google",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "192.168.100.1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "192.168.100.1" }
     ]
    }
   ]
  }
 ]
}