{
 "title": "Cardano: Application metrics v3",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Producer Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"producer0-exporter\"}",
     "legendFormat": "Load 1min"
    },
    {
     "expr": "node_load5{job=\"producer0-exporter\"}",
     "legendFormat": "Load 5min"
    },
    {
     "expr": "node_load15{job=\"producer0-exporter\"}",
     "legendFormat": "Load 15min"
    }
   ]
  },
  {
   "title": "Relay0 Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"relay0-exporter\"}",
     "legendFormat": "Load 1min"
    },
    {
     "expr": "node_load5{job=\"relay0-exporter\"}",
     "legendFormat": "Load 5min"
    },
    {
     "expr": "node_load15{job=\"relay0-exporter\"}",
     "legendFormat": "Load 15min"
    }
   ]
  },
  {
   "title": "Relay1 Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"relay1-exporter\"}",
     "legendFormat": "Load 1min"
    },
    {
     "expr": "node_load5{job=\"relay1-exporter\"}",
     "legendFormat": "Load 5min"
    },
    {
     "expr": "node_load15{job=\"relay1-exporter\"}",
     "legendFormat": "Load 15min"
    }
   ]
  },
  {
   "title": "CPU Utilization (1m avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Producer Status ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{mode=\"idle\", job=\"producer0-exporter\"}[1m]) * 100)",
     "legendFormat": "CPU Load {{cpu}}"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"producer0-exporter\"} / (node_memory_MemTotal_bytes{job=\"producer0-exporter\"})))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=\"producer0-exporter\"} / node_memory_SwapTotal_bytes{job=\"producer0-exporter\"})) * 100",
     "legendFormat": "Swap Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/home/lovelace/cardano-node\", job=\"producer0-exporter\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/home/lovelace/cardano-node\", job=\"producer0-exporter\"})",
     "legendFormat": "Disk Utilization "
    }
   ]
  },
  {
   "title": "Relay0 Status ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{mode=\"idle\", job=\"relay0-exporter\"}[1m]) * 100)",
     "legendFormat": "CPU Load {{cpu}}"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"relay0-exporter\"} / (node_memory_MemTotal_bytes{job=\"relay0-exporter\"})))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=\"relay0-exporter\"} / node_memory_SwapTotal_bytes{job=\"relay0-exporter\"})) * 100",
     "legendFormat": "Swap Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/home/lovelace/cardano-node\", job=\"relay0-exporter\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/home/lovelace/cardano-node\", job=\"relay0-exporter\"})",
     "legendFormat": "Disk Utilization "
    }
   ]
  },
  {
   "title": "Relay1 Status ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{mode=\"idle\", job=\"relay1-exporter\"}[1m]) * 100)",
     "legendFormat": "CPU Load {{cpu}}"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"relay1-exporter\"} / (node_memory_MemTotal_bytes{job=\"relay1-exporter\"})))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=\"relay1-exporter\"} / node_memory_SwapTotal_bytes{job=\"relay1-exporter\"})) * 100",
     "legendFormat": "Swap Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/home/lovelace/cardano-node\", job=\"relay1-exporter\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/home/lovelace/cardano-node\", job=\"relay1-exporter\"})",
     "legendFormat": "Disk Utilization "
    }
   ]
  },
  {
   "title": "Node Memory Used (%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{alias!~\"monitoring.*\"}  / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"}) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Bandwidth (bps)",
   "type": "graph",
   "description": "20 second rolling time average",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s])) * 8",
     "legendFormat": "Aggregate cluster ingress (received)"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "Aggregate cluster egress (transmit)"
    }
   ]
  },
  {
   "title": "Disk Utilization(%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/home/lovelace/cardano-node\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/home/lovelace/cardano-node\"})",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Node Bandwidth (bps)",
   "type": "graph",
   "description": "20 second rolling time average",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Node max \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node peak memory allocated (from OS, in MBytes)",
   "type": "graph",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(time()-node_boot_time_seconds)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} - node_memory_MemAvailable_bytes{alias!~\"monitoring.*\"})/1024/1024",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Last Block Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node Memory Available (%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias!~\"monitoring.*\"} / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node current \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Last Block Slot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Forged",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int"
    }
   ]
  },
  {
   "title": "Forged Num",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blocksForgedNum_int"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{job=\"producer0-cardano\"}",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "title": "Pool Performance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_Forge_forged_int / cardano_node_metrics_Forge_node_is_leader_int * 100)",
     "legendFormat": "Pool"
    }
   ]
  },
  {
   "title": "Cardano Service Restarts Per Hour",
   "type": "graph",
   "description": "Shows how many times cardano related services have been restarted within a 1 hour lookback window",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(increase(node_systemd_unit_state{name=~\"cardano.*|byron.*|explorer.*\",state=\"active\"}[1h:10s])) > 0",
     "legendFormat": "{{alias}}-{{name}}"
    }
   ]
  },
  {
   "title": "Adopted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_adopted_int"
    }
   ]
  },
  {
   "title": "Is Leader",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int"
    }
   ]
  },
  {
   "title": "About to Lead",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forge_about_to_lead_int"
    }
   ]
  },
  {
   "title": "About to Lead",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_Forge_forge_about_to_lead_int)/60/60"
    }
   ]
  },
  {
   "title": "Slot in Epoc",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((cardano_node_metrics_slotInEpoch_int{instance=\"producer0:12798\"}) / 432000) * 100"
    }
   ]
  },
  {
   "title": "Not Leader",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_not_leader_int"
    }
   ]
  },
  {
   "title": "Slots Missed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotsMissedNum_int"
    }
   ]
  },
  {
   "title": "Slot in Epoc",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{instance=\"producer0:12798\"}"
    }
   ]
  },
  {
   "title": "Slots Missed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotsMissedNum_int"
    }
   ]
  },
  {
   "title": "Slots to Epoc End",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_adopted_int"
    },
    {
     "expr": "cardano_node_metrics_blocksForgedNum_int"
    },
    {
     "expr": " cardano_node_metrics_Forge_node_is_leader_int"
    }
   ]
  },
  {
   "title": "Node RSS (allocated memory in RAM, in MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(cardano_node_metrics_Stat_rss_int*4096)/(1024*1026)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slots Missed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_slotsMissedNum_int[1h]) * 3600"
    }
   ]
  },
  {
   "title": "UxTxo Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(cardano_node_metrics_utxoSize_int)/1000000"
    }
   ]
  },
  {
   "title": "Slot leading share (% of slots led)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_Forge_node_is_leader_int[710s])/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[710s])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(cardano_node_metrics_Forge_node_is_leader_int[710s])/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[710s]))",
     "legendFormat": "Total led slots"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_blockNum_int[150s])*60",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(cardano_node_metrics_blockNum_int[150s])*60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Slot Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Rejected blocks since last restart",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int - cardano_node_metrics_Forge_adopted_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Chain Density",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[60s])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block Num",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 89 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}